- hosts: apache
  tasks:
    - name: Uninstall Apache server
      apt: name=apache2 purge=yes state=absent update_cache=yes
      become: yes

    - name: Remove leftover Apache2 packages
      apt: autoremove=yes purge=yes
      become: yes
